# Generated by Django 4.0 on 2021-12-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
