# Generated by Django 4.0 on 2021-12-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='uploads/')),
                ('short_description', models.CharField(max_length=250)),
                ('exam_date', models.DateField()),
                ('official_website_link', models.URLField()),
                ('registration_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('vacancies', models.IntegerField()),
                ('official_website_notification', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('latest_updates_links', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
