# Generated by Django 4.0 on 2021-12-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='sts',
            field=models.BooleanField(default=True),
        ),
    ]
